### ISSUE TITLE
Đổi thư viện cli trong file train.py

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/pos_tag#1]
Hiện tại file train.py đang sử dụng argparse

https://github.com/undertheseanlp/pos_tag/blob/5ac2de8f9b2a9a9081d3fcd9f077e770cad9c5ee/train.py#L1

Nên thay đổi sử dụng click giống underthesea

https://github.com/undertheseanlp/underthesea/blob/3663427da65e2b449e9135e3812edecb938b2319/underthesea/cli.py#L4

**Comment by HoLySoi** [comment]
không phải laf: $ cd word_tokenize
mà laf: $ cd pos_tag

**Comment by rain1024** [comment]
@HoLySoi Cảm ơn bạn đã comment, mình đã update nhé.
