### ISSUE TITLE
Lỗi không chạy được train and export model 

### ISSUE THREAD

**Issue by HuyKhoi-code** [undertheseanlp/pos_tag#4]
Sau khi đã xử lý tập train, khi mình chạy train and export model thì bị lỗi list index out of range ở phần X, y = transformer.transform(train_set). Ai gặp vấn đề tương tự có thể giúp mình hướng giải quyết được không ạ?

**Comment by HuyKhoi-code** [comment]
tập train đã qua xử lý 
[train.txt](https://github.com/undertheseanlp/pos_tag/files/5739002/train.txt)

**Comment by rain1024** [comment]
@HuyKhoi-code Anh thấy tập `train.txt` có vấn đề đối với dấu câu,

```
06	M
:	:
32	M
:	:
00	M

Đấu trường	N
vinh quang	A
-	-
Ngày	N
```

Em thử đổi nhãn của các dấu câu thành `PUNCT` (như `:`, `-`,.. ), rồi chạy lại nhé

**Comment by HuyKhoi-code** [comment]
> @HuyKhoi-code Anh thấy tập `train.txt` có vấn đề đối với dấu câu,
> 
> ```
> 06	M
> :	:
> 32	M
> :	:
> 00	M
> 
> Đấu trường	N
> vinh quang	A
> -	-
> Ngày	N
> ```
> 
> Em thử đổi nhãn của các dấu câu thành `PUNCT` (như `:`, `-`,.. ), rồi chạy lại nhé

Em đã đổi nhãn của dấu câu nhưng khi chạy thì nó chạy mãi không dừng. Khi em cắt tập train chỉ để lại 100 từ thì nó in ra lỗi là: UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 0: ordinal not in range(128). Em có thử encode = 'utf8' ở trong phần open file của preprocessvlsp2013.py nhưng vẫn không được ạ. Anh có thể giúp em hướng giải quyết được không ạ. 
Tập train sau khi được xử lý:
[train.txt](https://github.com/undertheseanlp/pos_tag/files/5742000/train.txt)

**Comment by rain1024** [comment]
> Em đã đổi nhãn của dấu câu nhưng khi chạy thì nó chạy mãi không dừng.

Nó chạy mãi không dừng có thể là đúng đó em. Với khoảng 10k câu thì nó cần phải extract features mất vài phút
